[package]
name = "csaf-schema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

[lib]
path = "generated/lib.rs"

[dependencies]

[features]
default = ["csaf2_0", "csaf2_1"]
csaf2_0 = []
csaf2_1 = []

[lints]
workspace = true
