[package]
name = "csaf-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

[dependencies]
csaf-schema = { path = "../csaf-schema" } # contains base types, so always needed
csaf-validation = { path = "../csaf-validation", features = [
    "cli",
] } # contains semantic validation, so should be needed most of the times
csaf-conversion = { path = "../csaf-conversion", features = [
    "cli",
], optional = true }
clap.workspace = true

[features]
default = ["conversion"]
conversion = ["dep:csaf-conversion"]

[lints]
workspace = true
